---
driver:
  name: azurerm

driver_config:
  location: 'Central US'
  machine_size: 'Standard_D2s_v3'

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm
  - name: Windows-2012r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[ohai_ms_licensing::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
